# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find2run', '0003_auto_20170624_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find2run.User'),
        ),
    ]
